services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://symfony:password@db:3306/symfony_db
      - MAILER_DSN=smtp://mailhog:1025
      - WEEKLY_NEWS_EMAIL=your-email@example.com
    depends_on:
      - db
      - mailhog
    networks:
      - symfony_network
    command: php -S 0.0.0.0:8000 -t public

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_cron
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://symfony:password@db:3306/symfony_db
      - MAILER_DSN=smtp://mailhog:1025
      - WEEKLY_NEWS_EMAIL=test@localhost.com
    depends_on:
      - db
      - mailhog
    networks:
      - symfony_network
    command: >
      sh -c "
        echo '0 9 * * 1 cd /var/www/html && /usr/local/bin/php bin/console app:weekly-news-email >> /var/log/cron.log 2>&1' | crontab - &&
        cron -f
      "

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - symfony_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - symfony_network

  mailhog:
    image: mailhog/mailhog
    container_name: symfony_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - symfony_network    

volumes:
  db_data:

networks:
  symfony_network:
    driver: bridge