App\Entity\Comment:
    type: entity
    table: comment
    repositoryClass: App\Repository\CommentRepository
    lifecycleCallbacks:
        prePersist: [setTimestamps]
        preUpdate: [updateTimestamp]

    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

        name:
            type: string
            length: 255

        email:
            type: string
            length: 255

        content:
            type: text

        createdAt:
            type: datetime_immutable

        updatedAt:
            type: datetime_immutable

    manyToOne:
        news:
            targetEntity: App\Entity\News
            inversedBy: comments
            joinColumn:
                nullable: false